# PDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
#
# Modified archive of the p4lang-project (github.com/p4lang/tutorials/exercises/multicast) repository 
#
#
# 	Author: Wai Yan Kyaw <waiyankyawbelu2020@gmail.com>
# 	Date:   24 September 2023



BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = scenario/topology.json

include ../utils/Makefile
