# PDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
#
# Modified archive of the p4lang-project (github.com/p4lang/tutorials/) repository 
# for purely academic purposes. 
#
# 	Author: Wai Yan Kyaw <waiyankyawbelu2020@gmail.com
# 	Date:   25 Dec 2023



BMV2_SWITCH_EXE = simple_switch_grpc

include ../utils/Makefile